version: "3.8"
services:
    bot:
        image: registry.groosha.space/shared/passgenbot:latest
        restart: always
        depends_on:
            - redis
        volumes:
            - "bot-config:/app/config"
    redis:
        image: redis:6.0-alpine
        volumes:
            - "redis-config:/usr/local/etc/redis"
            - "redis-data:/data"
        command: "redis-server /usr/local/etc/redis/redis.conf"

volumes:
    bot-config:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: './bot-config'
    redis-config:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: './redis-config'
    redis-data:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: './redis-data'